version: "3"

networks:
 dockersql-network:
  driver: bridge

services:
 api.bank.system:
  container_name: api.bank
  build:
   context: .
   dockerfile: BankSystem/Dockerfile
  networks:
   - dockersql-network
  depends_on:
   - mssql-server
   
 mssql-server:
  image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  networks:
   - dockersql-network